// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { AllFieldGroth16VerifierSystem } from "../../systems/AllFieldGroth16VerifierSystem.sol";
import { FullVerifyZKProofParams } from "../../systems/types.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type AllFieldGroth16VerifierSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "evefrontier", name: "AllFieldGroth16V" }))
AllFieldGroth16VerifierSystemType constant allFieldGroth16VerifierSystem = AllFieldGroth16VerifierSystemType.wrap(
  0x737965766566726f6e74696572000000416c6c4669656c6447726f7468313656
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title AllFieldGroth16VerifierSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library AllFieldGroth16VerifierSystemLib {
  error AllFieldGroth16VerifierSystemLib_CallingFromRootSystem();

  function verifyProof(
    AllFieldGroth16VerifierSystemType self,
    FullVerifyZKProofParams calldata verifyZKProofParams
  ) internal view returns (bool) {
    return CallWrapper(self.toResourceId(), address(0)).verifyProof(verifyZKProofParams);
  }

  function verifyProof(
    CallWrapper memory self,
    FullVerifyZKProofParams calldata verifyZKProofParams
  ) internal view returns (bool) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert AllFieldGroth16VerifierSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_verifyProof_FullVerifyZKProofParams.verifyProof, (verifyZKProofParams));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    return abi.decode(result, (bool));
  }

  function verifyProof(
    RootCallWrapper memory self,
    FullVerifyZKProofParams calldata verifyZKProofParams
  ) internal view returns (bool) {
    bytes memory systemCall = abi.encodeCall(_verifyProof_FullVerifyZKProofParams.verifyProof, (verifyZKProofParams));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    return abi.decode(result, (bool));
  }

  function callFrom(AllFieldGroth16VerifierSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(AllFieldGroth16VerifierSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), msg.sender);
  }

  function callAsRootFrom(
    AllFieldGroth16VerifierSystemType self,
    address from
  ) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(AllFieldGroth16VerifierSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(AllFieldGroth16VerifierSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (AllFieldGroth16VerifierSystemType) {
    return AllFieldGroth16VerifierSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(AllFieldGroth16VerifierSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _verifyProof_FullVerifyZKProofParams {
  function verifyProof(FullVerifyZKProofParams calldata verifyZKProofParams) external;
}

using AllFieldGroth16VerifierSystemLib for AllFieldGroth16VerifierSystemType global;
using AllFieldGroth16VerifierSystemLib for CallWrapper global;
using AllFieldGroth16VerifierSystemLib for RootCallWrapper global;
