// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Groth16VerifierCoreSystem } from "../../systems/Groth16VerifierCoreSystem.sol";
import { VerifyZKProofParams } from "../../systems/types.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type Groth16VerifierCoreSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "evefrontier", name: "Groth16VerifierC" }))
Groth16VerifierCoreSystemType constant groth16VerifierCoreSystem = Groth16VerifierCoreSystemType.wrap(
  0x737965766566726f6e7469657200000047726f74683136566572696669657243
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title Groth16VerifierCoreSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library Groth16VerifierCoreSystemLib {
  error Groth16VerifierCoreSystemLib_CallingFromRootSystem();

  function verifyProof(
    Groth16VerifierCoreSystemType self,
    VerifyZKProofParams calldata verifyZKProofParams
  ) internal view returns (bool) {
    return CallWrapper(self.toResourceId(), address(0)).verifyProof(verifyZKProofParams);
  }

  function verifyProof(
    CallWrapper memory self,
    VerifyZKProofParams calldata verifyZKProofParams
  ) internal view returns (bool) {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert Groth16VerifierCoreSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_verifyProof_VerifyZKProofParams.verifyProof, (verifyZKProofParams));
    bytes memory worldCall = self.from == address(0)
      ? abi.encodeCall(IWorldCall.call, (self.systemId, systemCall))
      : abi.encodeCall(IWorldCall.callFrom, (self.from, self.systemId, systemCall));
    (bool success, bytes memory returnData) = address(_world()).staticcall(worldCall);
    if (!success) revertWithBytes(returnData);

    bytes memory result = abi.decode(returnData, (bytes));
    return abi.decode(result, (bool));
  }

  function verifyProof(
    RootCallWrapper memory self,
    VerifyZKProofParams calldata verifyZKProofParams
  ) internal view returns (bool) {
    bytes memory systemCall = abi.encodeCall(_verifyProof_VerifyZKProofParams.verifyProof, (verifyZKProofParams));

    bytes memory result = SystemCall.staticcallOrRevert(self.from, self.systemId, systemCall);
    return abi.decode(result, (bool));
  }

  function callFrom(Groth16VerifierCoreSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(Groth16VerifierCoreSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), msg.sender);
  }

  function callAsRootFrom(
    Groth16VerifierCoreSystemType self,
    address from
  ) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(Groth16VerifierCoreSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(Groth16VerifierCoreSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (Groth16VerifierCoreSystemType) {
    return Groth16VerifierCoreSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(Groth16VerifierCoreSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _verifyProof_VerifyZKProofParams {
  function verifyProof(VerifyZKProofParams calldata verifyZKProofParams) external;
}

using Groth16VerifierCoreSystemLib for Groth16VerifierCoreSystemType global;
using Groth16VerifierCoreSystemLib for CallWrapper global;
using Groth16VerifierCoreSystemLib for RootCallWrapper global;
