// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { VerifiedPOD, VerifiedPODData } from "./tables/VerifiedPOD.sol";
import { MerkleLeafFieldMap } from "./tables/MerkleLeafFieldMap.sol";
import { Ship } from "./tables/Ship.sol";
import { Inventory } from "./tables/Inventory.sol";
import { InventoryItem, InventoryItemData } from "./tables/InventoryItem.sol";
