// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

library MerkleLeafFieldMap {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "evefrontier", name: "MerkleLeafFieldM", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746265766566726f6e746965720000004d65726b6c654c6561664669656c644d);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0000000100000000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32, bytes32)
  Schema constant _keySchema = Schema.wrap(0x004002005f5f0000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (string)
  Schema constant _valueSchema = Schema.wrap(0x00000001c5000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](2);
    keyNames[0] = "podTypeId";
    keyNames[1] = "fieldId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](1);
    fieldNames[0] = "field";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get field.
   */
  function getField(bytes32 podTypeId, bytes32 fieldId) internal view returns (string memory field) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get field.
   */
  function _getField(bytes32 podTypeId, bytes32 fieldId) internal view returns (string memory field) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get field.
   */
  function get(bytes32 podTypeId, bytes32 fieldId) internal view returns (string memory field) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    bytes memory _blob = StoreSwitch.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Get field.
   */
  function _get(bytes32 podTypeId, bytes32 fieldId) internal view returns (string memory field) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    bytes memory _blob = StoreCore.getDynamicField(_tableId, _keyTuple, 0);
    return (string(_blob));
  }

  /**
   * @notice Set field.
   */
  function setField(bytes32 podTypeId, bytes32 fieldId, string memory field) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((field)));
  }

  /**
   * @notice Set field.
   */
  function _setField(bytes32 podTypeId, bytes32 fieldId, string memory field) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((field)));
  }

  /**
   * @notice Set field.
   */
  function set(bytes32 podTypeId, bytes32 fieldId, string memory field) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreSwitch.setDynamicField(_tableId, _keyTuple, 0, bytes((field)));
  }

  /**
   * @notice Set field.
   */
  function _set(bytes32 podTypeId, bytes32 fieldId, string memory field) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreCore.setDynamicField(_tableId, _keyTuple, 0, bytes((field)));
  }

  /**
   * @notice Get the length of field.
   */
  function lengthField(bytes32 podTypeId, bytes32 fieldId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of field.
   */
  function _lengthField(bytes32 podTypeId, bytes32 fieldId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of field.
   */
  function length(bytes32 podTypeId, bytes32 fieldId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    uint256 _byteLength = StoreSwitch.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get the length of field.
   */
  function _length(bytes32 podTypeId, bytes32 fieldId) internal view returns (uint256) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    uint256 _byteLength = StoreCore.getDynamicFieldLength(_tableId, _keyTuple, 0);
    unchecked {
      return _byteLength / 1;
    }
  }

  /**
   * @notice Get an item of field.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItemField(bytes32 podTypeId, bytes32 fieldId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of field.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItemField(bytes32 podTypeId, bytes32 fieldId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of field.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function getItem(bytes32 podTypeId, bytes32 fieldId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    unchecked {
      bytes memory _blob = StoreSwitch.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Get an item of field.
   * @dev Reverts with Store_IndexOutOfBounds if `_index` is out of bounds for the array.
   */
  function _getItem(bytes32 podTypeId, bytes32 fieldId, uint256 _index) internal view returns (string memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    unchecked {
      bytes memory _blob = StoreCore.getDynamicFieldSlice(_tableId, _keyTuple, 0, _index * 1, (_index + 1) * 1);
      return (string(_blob));
    }
  }

  /**
   * @notice Push a slice to field.
   */
  function pushField(bytes32 podTypeId, bytes32 fieldId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to field.
   */
  function _pushField(bytes32 podTypeId, bytes32 fieldId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to field.
   */
  function push(bytes32 podTypeId, bytes32 fieldId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreSwitch.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Push a slice to field.
   */
  function _push(bytes32 podTypeId, bytes32 fieldId, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreCore.pushToDynamicField(_tableId, _keyTuple, 0, bytes((_slice)));
  }

  /**
   * @notice Pop a slice from field.
   */
  function popField(bytes32 podTypeId, bytes32 fieldId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from field.
   */
  function _popField(bytes32 podTypeId, bytes32 fieldId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from field.
   */
  function pop(bytes32 podTypeId, bytes32 fieldId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreSwitch.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Pop a slice from field.
   */
  function _pop(bytes32 podTypeId, bytes32 fieldId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreCore.popFromDynamicField(_tableId, _keyTuple, 0, 1);
  }

  /**
   * @notice Update a slice of field at `_index`.
   */
  function updateField(bytes32 podTypeId, bytes32 fieldId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of field at `_index`.
   */
  function _updateField(bytes32 podTypeId, bytes32 fieldId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of field at `_index`.
   */
  function update(bytes32 podTypeId, bytes32 fieldId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreSwitch.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Update a slice of field at `_index`.
   */
  function _update(bytes32 podTypeId, bytes32 fieldId, uint256 _index, string memory _slice) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    unchecked {
      bytes memory _encoded = bytes((_slice));
      StoreCore.spliceDynamicData(_tableId, _keyTuple, 0, uint40(_index * 1), uint40(_encoded.length), _encoded);
    }
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 podTypeId, bytes32 fieldId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 podTypeId, bytes32 fieldId) internal {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack dynamic data lengths using this table's schema.
   * @return _encodedLengths The lengths of the dynamic fields (packed into a single bytes32 value).
   */
  function encodeLengths(string memory field) internal pure returns (EncodedLengths _encodedLengths) {
    // Lengths are effectively checked during copy by 2**40 bytes exceeding gas limits
    unchecked {
      _encodedLengths = EncodedLengthsLib.pack(bytes(field).length);
    }
  }

  /**
   * @notice Tightly pack dynamic (variable length) data using this table's schema.
   * @return The dynamic data, encoded into a sequence of bytes.
   */
  function encodeDynamic(string memory field) internal pure returns (bytes memory) {
    return abi.encodePacked(bytes((field)));
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(string memory field) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData;
    EncodedLengths _encodedLengths = encodeLengths(field);
    bytes memory _dynamicData = encodeDynamic(field);

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 podTypeId, bytes32 fieldId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](2);
    _keyTuple[0] = podTypeId;
    _keyTuple[1] = fieldId;

    return _keyTuple;
  }
}
