import type { DetailedSmartAssembly, SolarSystemLocation } from "../../../src/types/gameData";

/**
 * Re-export DetailedSmartAssembly for use within this package.
 */
export type { DetailedSmartAssembly };

/**
 * Interface for the mock ship location data before POD conversion.
 */
export interface ShipLocationData {
  shipId: string; // Use string for large ID representation
  solarSystemId: number;
  location: SolarSystemLocation;
  interactionDistance: bigint; // Store as BigInt
  timestamp: number; // Unix timestamp in milliseconds
}

/**
 * Interface for the eventual distance assertion data (not generated by the mock script).
 */
export interface DistanceAssertionData {
  objectA_ID: string;
  objectB_ID: string;
  distanceMetric: bigint; // e.g., distance squared
  calculationTimestamp: number;
} 