// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { FullVerifyZKProofParams } from "../../namespaces/evefrontier/systems/types.sol";

/**
 * @title IAllFieldGroth16VerifierSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAllFieldGroth16VerifierSystem {
  function evefrontier__verifyProof(FullVerifyZKProofParams calldata verifyZKProofParams) external view returns (bool);
}
