// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { VerifyZKProofParams } from "../../namespaces/evefrontier/systems/types.sol";

/**
 * @title IGroth16VerifierCoreSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IGroth16VerifierCoreSystem {
  function evefrontier__verifyProof(VerifyZKProofParams calldata verifyZKProofParams) external view returns (bool);
}
