// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { InventoryItemParams } from "../../namespaces/evefrontier/systems/types.sol";

/**
 * @title IInventorySystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IInventorySystem {
  function evefrontier__depositInventory(uint256 smartObjectId, InventoryItemParams[] calldata items) external;

  function evefrontier__withdrawInventory(uint256 smartObjectId, InventoryItemParams[] calldata items) external;
}
