// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { FullVerifyZKProofParams, DistanceAttestationParams } from "../../namespaces/evefrontier/systems/types.sol";

/**
 * @title IPoseidonAttestationSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IPoseidonAttestationSystem {
  error PoseidonAttestation_ZKProofInvalid();
  error PoseidonAttestation_ZKSignerInvalid();
  error PoseidonAttestation_DistanceSquaredMetersInvalid();
  error PoseidonAttestation_PodDataTypeInvalid();
  error PoseidonAttestation_StaleTimestamp();

  function evefrontier__poseidonAttestation(
    uint256 smartObjectId,
    uint256 toObjectId,
    FullVerifyZKProofParams calldata verifyZKProofParams,
    DistanceAttestationParams calldata distanceAttestationParams
  ) external;
}
